package main

import (
	"context"
	"fmt"
	"log"
	"sync"
	"time"
)

// TaskResult 任务结果集
type TaskResult struct {
	Title   string // 标题
	Content string // 正文
	Err     error
}

// TaskProcessor 任务处理器结构体
type TaskProcessor struct {
	maxConcurrent int           // 最大并发数
	limit         chan struct{} // 限流信号
	timeout       time.Duration // 超时时间

	wg sync.WaitGroup
}

// NewTaskProcessor 初始化任务处理器
func NewTaskProcessor(maxConcurrent int, timeout time.Duration) *TaskProcessor {
	if maxConcurrent <= 0 {
		maxConcurrent = 1
	}
	if timeout <= 0 {
		timeout = 30 * time.Second
	}

	return &TaskProcessor{
		maxConcurrent: maxConcurrent,
		limit:         make(chan struct{}, maxConcurrent),
		timeout:       timeout,
	}
}

// Run 运行逻辑
func (p *TaskProcessor) Run(titles []string) {
	log.Printf("Starting %d task(s)", len(titles))
	jobs := make(chan string, len(titles))
	results := make(chan TaskResult, len(titles))

	// 开启协程收集任务处理结果
	collectDone := make(chan struct{})
	go func() {
		defer close(collectDone)
		for result := range results {
			if result.Err != nil {
				log.Printf("[ERROR] %s", result.Err)
				continue
			}
			// log.Printf("[INFO] OK! title: %s", result.Title)
			log.Printf("[INFO] OK! %s", result.Content)
		}
	}()

	// 防止 titles 数量过大，使用异步进行分发
	go func() {
		for _, title := range titles {
			jobs <- title
		}
		close(jobs)
	}()

	// 启动 worker
	for i := 0; i < p.maxConcurrent; i++ {
		p.wg.Add(1)
		go p.worker(jobs, results)
	}

	p.wg.Wait()
	close(results)

	<-collectDone
	fmt.Printf("Finished %d task(s)", len(titles))
}

// worker 处理任务 worker
func (p *TaskProcessor) worker(jobs <-chan string, results chan<- TaskResult) {
	defer p.wg.Done()

	for title := range jobs {
		p.limit <- struct{}{} // 占位信号，限流

		ctx, cancel := context.WithTimeout(context.Background(), p.timeout)

		content, err := p.mockGenerateAI(ctx, title)

		// 写入结果
		results <- TaskResult{
			Title:   title,
			Content: content,
			Err:     err,
		}

		// 处理完成，清理 Context 并释放信号
		cancel()
		<-p.limit
	}
}

// mockGenerateAI
func (p *TaskProcessor) mockGenerateAI(ctx context.Context, title string) (string, error) {
	select {
	case <-time.After(4 * time.Second):
		return fmt.Sprintf("Title: %s Generated AI Content: This is content generated by simulated AI", title), nil
	case <-ctx.Done():
		return "", ctx.Err()
	}
}

// mockGenerateTitle 模拟生成标题集
func mockGenerateTitle() []string {
	var titles []string
	for i := 0; i < 20; i++ {
		titles = append(titles, fmt.Sprintf("Chapter %d", i))
	}
	return titles
}

func main() {
	titles := mockGenerateTitle()

	p := NewTaskProcessor(5, 5*time.Second)
	p.Run(titles)
}
